id: IF1D457C5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T21:14:43+00:00'
last_modified: '2022-06-08T10:17:39.596582+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22936
  title: སྐྱེས་རབས་བརྒྱ་ལྔ་བཅུ་པ། ༼སྡེ་དགེ་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    760D:
      image_group_id: I1KG9120
      title: ''
      total_pages: 370
      order: 1
      base_file: 760D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
