id: P009336
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22936
  title: སྐྱེས་རབས་བརྒྱ་ལྔ་བཅུ་པ། ༼སྡེ་དགེ་པར་མ།༽
  author: ''
  volumes:
    8d3c50deac68441e93995fffe0ab429d:
      image_group_id: I1KG9120
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
